import * as Blockly from 'blockly/core';

function keyOptions(): [string, string][] {
  const base: [string, string][] = [
    ['spasi', ' '],
    ['panah atas', 'ArrowUp'],
    ['panah bawah', 'ArrowDown'],
    ['panah kiri', 'ArrowLeft'],
    ['panah kanan', 'ArrowRight'],
  ];
  for (let c = 97; c <= 122; c++) base.push([String.fromCharCode(c), String.fromCharCode(c)]);
  for (let d = 0; d <= 9; d++) base.push([String(d), String(d)]);
  return base;
}

let getCostumeOptions: () => [string, string][] = () => [['kostum1', '0']];
export function setCostumeOptionsProvider(fn: () => [string, string][]): void {
  getCostumeOptions = fn;
}

export const SPRITE_BLOCK_TYPES = [
  'sprite_hat_green_flag',
  'sprite_hat_clicked',
  'sprite_hat_key',
  'sprite_hat_receive',
  'sprite_broadcast',
  'sprite_broadcast_wait',
  'sprite_move',
  'sprite_turn_right',
  'sprite_turn_left',
  'sprite_goto_xy',
  'sprite_change_x',
  'sprite_change_y',
  'sprite_point_direction',
  'sprite_glide',
  'sprite_bounce_edge',
  'sprite_say',
  'sprite_say_for',
  'sprite_say_clear',
  'sprite_switch_costume',
  'sprite_next_costume',
  'sprite_change_size',
  'sprite_set_size',
  'sprite_show',
  'sprite_hide',
  'sprite_wait',
  'sprite_repeat',
  'sprite_forever',
  'sprite_if',
  'sprite_if_else',
  'sprite_wait_until',
  'sprite_stop',
  'sprite_op_arith',
  'sprite_op_mod',
  'sprite_op_compare',
  'sprite_op_and',
  'sprite_op_or',
  'sprite_op_not',
  'sprite_op_random',
  'sprite_op_join',
  'sprite_op_length',
  'sprite_sensing_key',
  'sprite_sensing_timer',
  'sprite_sensing_reset_timer',
] as const;

export function registerSpriteBlocks(): void {
  Blockly.defineBlocksWithJsonArray([
    {
      type: 'sprite_hat_green_flag',
      message0: 'saat bendera hijau diklik',
      nextStatement: null,
      style: 'events_blocks',
    },
    {
      type: 'sprite_hat_clicked',
      message0: 'saat sprite ini diklik',
      nextStatement: null,
      style: 'events_blocks',
    },
    {
      type: 'sprite_hat_key',
      message0: 'saat tombol %1 ditekan',
      args0: [{ type: 'field_dropdown', name: 'KEY', options: keyOptions() }],
      nextStatement: null,
      style: 'events_blocks',
    },
    {
      type: 'sprite_hat_receive',
      message0: 'saat terima pesan %1',
      args0: [{ type: 'field_input', name: 'MSG', text: 'pesan1' }],
      nextStatement: null,
      style: 'events_blocks',
    },
    {
      type: 'sprite_broadcast',
      message0: 'kirim pesan %1',
      args0: [{ type: 'field_input', name: 'MSG', text: 'pesan1' }],
      previousStatement: null,
      nextStatement: null,
      style: 'events_blocks',
    },
    {
      type: 'sprite_broadcast_wait',
      message0: 'kirim pesan %1 dan tunggu',
      args0: [{ type: 'field_input', name: 'MSG', text: 'pesan1' }],
      previousStatement: null,
      nextStatement: null,
      style: 'events_blocks',
    },
    {
      type: 'sprite_move',
      message0: 'gerak %1 langkah',
      args0: [{ type: 'input_value', name: 'STEPS', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_turn_right',
      message0: 'putar ↻ %1 derajat',
      args0: [{ type: 'input_value', name: 'DEG', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_turn_left',
      message0: 'putar ↺ %1 derajat',
      args0: [{ type: 'input_value', name: 'DEG', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_goto_xy',
      message0: 'ke x: %1 y: %2',
      args0: [
        { type: 'input_value', name: 'X', check: 'Number' },
        { type: 'input_value', name: 'Y', check: 'Number' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_change_x',
      message0: 'ubah x %1',
      args0: [{ type: 'input_value', name: 'DX', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_change_y',
      message0: 'ubah y %1',
      args0: [{ type: 'input_value', name: 'DY', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_point_direction',
      message0: 'arah ke %1',
      args0: [{ type: 'input_value', name: 'DIR', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_glide',
      message0: 'luncur %1 detik ke x: %2 y: %3',
      args0: [
        { type: 'input_value', name: 'SECS', check: 'Number' },
        { type: 'input_value', name: 'X', check: 'Number' },
        { type: 'input_value', name: 'Y', check: 'Number' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_bounce_edge',
      message0: 'jika di tepi, pantul',
      previousStatement: null,
      nextStatement: null,
      style: 'motion_blocks',
    },
    {
      type: 'sprite_say',
      message0: 'katakan %1',
      args0: [{ type: 'input_value', name: 'TEXT' }],
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_say_for',
      message0: 'katakan %1 selama %2 detik',
      args0: [
        { type: 'input_value', name: 'TEXT' },
        { type: 'input_value', name: 'SECS', check: 'Number' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_say_clear',
      message0: 'sembunyikan gelembung',
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_switch_costume',
      message0: 'ganti kostum ke %1',
      args0: [{ type: 'field_dropdown', name: 'COSTUME', options: () => getCostumeOptions() }],
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_next_costume',
      message0: 'kostum berikutnya',
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_change_size',
      message0: 'ubah ukuran %1',
      args0: [{ type: 'input_value', name: 'DELTA', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_set_size',
      message0: 'atur ukuran ke %1 %',
      args0: [{ type: 'input_value', name: 'PCT', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_show',
      message0: 'tampil',
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_hide',
      message0: 'sembunyi',
      previousStatement: null,
      nextStatement: null,
      style: 'looks_blocks',
    },
    {
      type: 'sprite_wait',
      message0: 'tunggu %1 detik',
      args0: [{ type: 'input_value', name: 'SECS', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
    },
    {
      type: 'sprite_repeat',
      message0: 'ulangi %1 kali %2 %3',
      args0: [
        { type: 'input_value', name: 'TIMES', check: 'Number' },
        { type: 'input_dummy' },
        { type: 'input_statement', name: 'DO' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
    },
    {
      type: 'sprite_forever',
      message0: 'ulangi terus %1 %2',
      args0: [{ type: 'input_dummy' }, { type: 'input_statement', name: 'DO' }],
      previousStatement: null,
      style: 'control_blocks',
    },
    {
      type: 'sprite_if',
      message0: 'jika %1 maka %2 %3',
      args0: [
        { type: 'input_value', name: 'COND', check: 'Boolean' },
        { type: 'input_dummy' },
        { type: 'input_statement', name: 'DO' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
    },
    {
      type: 'sprite_if_else',
      message0: 'jika %1 maka %2 %3 kalau tidak %4',
      args0: [
        { type: 'input_value', name: 'COND', check: 'Boolean' },
        { type: 'input_dummy' },
        { type: 'input_statement', name: 'DO' },
        { type: 'input_statement', name: 'ELSE' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
    },
    {
      type: 'sprite_wait_until',
      message0: 'tunggu sampai %1',
      args0: [{ type: 'input_value', name: 'COND', check: 'Boolean' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
    },
    {
      type: 'sprite_stop',
      message0: 'hentikan %1',
      args0: [
        {
          type: 'field_dropdown',
          name: 'TARGET',
          options: [
            ['semua', 'all'],
            ['skrip ini', 'this'],
            ['skrip lain di sprite ini', 'others'],
          ],
        },
      ],
      previousStatement: null,
      style: 'control_blocks',
    },
    {
      type: 'sprite_op_arith',
      message0: '%1 %2 %3',
      args0: [
        { type: 'input_value', name: 'A', check: 'Number' },
        {
          type: 'field_dropdown',
          name: 'OP',
          options: [
            ['+', 'add'],
            ['−', 'sub'],
            ['×', 'mul'],
            ['÷', 'div'],
          ],
        },
        { type: 'input_value', name: 'B', check: 'Number' },
      ],
      output: 'Number',
      inputsInline: true,
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_mod',
      message0: 'sisa dari %1 : %2',
      args0: [
        { type: 'input_value', name: 'A', check: 'Number' },
        { type: 'input_value', name: 'B', check: 'Number' },
      ],
      output: 'Number',
      inputsInline: true,
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_compare',
      message0: '%1 %2 %3',
      args0: [
        { type: 'input_value', name: 'A' },
        {
          type: 'field_dropdown',
          name: 'OP',
          options: [
            ['<', 'lt'],
            ['=', 'eq'],
            ['>', 'gt'],
          ],
        },
        { type: 'input_value', name: 'B' },
      ],
      output: 'Boolean',
      inputsInline: true,
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_and',
      message0: '%1 dan %2',
      args0: [
        { type: 'input_value', name: 'A', check: 'Boolean' },
        { type: 'input_value', name: 'B', check: 'Boolean' },
      ],
      output: 'Boolean',
      inputsInline: true,
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_or',
      message0: '%1 atau %2',
      args0: [
        { type: 'input_value', name: 'A', check: 'Boolean' },
        { type: 'input_value', name: 'B', check: 'Boolean' },
      ],
      output: 'Boolean',
      inputsInline: true,
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_not',
      message0: 'tidak %1',
      args0: [{ type: 'input_value', name: 'A', check: 'Boolean' }],
      output: 'Boolean',
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_random',
      message0: 'acak %1 sampai %2',
      args0: [
        { type: 'input_value', name: 'FROM', check: 'Number' },
        { type: 'input_value', name: 'TO', check: 'Number' },
      ],
      output: 'Number',
      inputsInline: true,
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_join',
      message0: 'gabung %1 %2',
      args0: [
        { type: 'input_value', name: 'A' },
        { type: 'input_value', name: 'B' },
      ],
      output: 'String',
      inputsInline: true,
      style: 'operators_blocks',
    },
    {
      type: 'sprite_op_length',
      message0: 'panjang %1',
      args0: [{ type: 'input_value', name: 'A' }],
      output: 'Number',
      style: 'operators_blocks',
    },
    {
      type: 'sprite_sensing_key',
      message0: 'tombol %1 ditekan?',
      args0: [{ type: 'field_dropdown', name: 'KEY', options: keyOptions() }],
      output: 'Boolean',
      style: 'sensing_blocks',
    },
    {
      type: 'sprite_sensing_timer',
      message0: 'pengatur waktu',
      output: 'Number',
      style: 'sensing_blocks',
    },
    {
      type: 'sprite_sensing_reset_timer',
      message0: 'reset pengatur waktu',
      previousStatement: null,
      nextStatement: null,
      style: 'sensing_blocks',
    },
  ]);
}
