import * as Blockly from 'blockly/core';

const COLOR_OPTIONS: [string, string][] = [
  ['hitam', '#000000'],
  ['putih', '#ffffff'],
  ['merah', '#e53935'],
  ['jingga', '#fb8c00'],
  ['kuning', '#fdd835'],
  ['hijau', '#43a047'],
  ['biru', '#1e88e5'],
  ['ungu', '#8e24aa'],
  ['merah muda', '#ec407a'],
  ['abu-abu', '#9e9e9e'],
];

let getAssetOptions: () => [string, string][] = () => [['(tidak ada gambar)', '']];

export function setHtmlAssetOptionsProvider(fn: () => [string, string][]): void {
  getAssetOptions = fn;
}

export const HTML_BLOCK_TYPES = [
  'html_document',
  'html_head',
  'html_body',
  'html_title',
  'html_section',
  'html_row',
  'html_heading',
  'html_paragraph',
  'html_list',
  'html_list_item',
  'html_table',
  'html_table_row',
  'html_table_cell',
  'html_list_ordered',
  'html_header',
  'html_main',
  'html_footer',
  'html_text',
  'html_image_asset',
  'html_image_url',
  'html_link',
  'html_button',
  'html_hr',
  'html_style_color',
  'html_style_bg',
  'html_style_align',
  'html_style_size',
  'html_style_bold',
  'html_style_italic',
  'html_style_padding',
  'html_style_margin',
  'html_style_radius',
  'html_style_shadow',
  'html_style_font',
] as const;

export function registerHtmlBlocks(): void {
  Blockly.defineBlocksWithJsonArray([
    {
      type: 'html_document',
      message0: '<html> %1 </html>',
      args0: [{ type: 'input_statement', name: 'CONTENT' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Kerangka satu halaman HTML lengkap (<html>).',
    },
    {
      type: 'html_head',
      message0: '<head> %1 </head>',
      args0: [{ type: 'input_statement', name: 'CONTENT' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Bagian info halaman yang tak tampil di layar, mis. judul tab (<head>).',
    },
    {
      type: 'html_body',
      message0: '<body> %1 </body>',
      args0: [{ type: 'input_statement', name: 'CONTENT' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Isi halaman yang tampil di layar (<body>).',
    },
    {
      type: 'html_title',
      message0: '<title> %1 </title>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Judul halaman yang muncul di tab browser (<title>).',
    },
    {
      type: 'html_section',
      tooltip: 'Satu bagian halaman untuk mengelompokkan isi (<section>).',
      message0: '<section> %1 </section>',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_row',
      tooltip: 'Membuat isinya berjajar ke samping, bukan menumpuk ke bawah (<div> sejajar/flex).',
      message0: '<div> berjajar: %1 %2 </div>',
      args0: [
        {
          type: 'field_dropdown',
          name: 'JUSTIFY',
          options: [
            ['rata kiri', 'flex-start'],
            ['tengah', 'center'],
            ['rata kanan', 'flex-end'],
            ['renggang', 'space-between'],
            ['sebar rata', 'space-around'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_heading',
      tooltip: 'Judul bagian dengan ukuran h1, h2, atau h3 (<h1>).',
      message0: '%1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'LEVEL',
          options: [
            ['<h1>', 'h1'],
            ['<h2>', 'h2'],
            ['<h3>', 'h3'],
            ['<h4>', 'h4'],
            ['<h5>', 'h5'],
            ['<h6>', 'h6'],
          ],
        },
        { type: 'input_value', name: 'TEXT', check: 'String' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_paragraph',
      tooltip: 'Satu paragraf teks (<p>).',
      message0: '<p> %1 </p>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_list',
      tooltip: 'Daftar berpoin (<ul>) — isi dengan blok <li>.',
      message0: '<ul> %1 </ul>',
      args0: [{ type: 'input_statement', name: 'ITEMS' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_list_item',
      tooltip: 'Satu butir di dalam daftar (<li>).',
      message0: '<li> %1 </li>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_table',
      tooltip: 'Tabel untuk menyusun data dalam baris dan kolom (<table>), bergaris.',
      message0: '<table> garis: %1 %2 %3 %4 </table>',
      args0: [
        {
          type: 'field_dropdown',
          name: 'BORDER_WIDTH',
          options: [
            ['tipis', '1px'],
            ['sedang', '2px'],
            ['tebal', '4px'],
            ['tidak ada', '0'],
          ],
        },
        {
          type: 'field_dropdown',
          name: 'BORDER_STYLE',
          options: [
            ['penuh', 'solid'],
            ['putus-putus', 'dashed'],
            ['titik-titik', 'dotted'],
          ],
        },
        { type: 'field_dropdown', name: 'BORDER_COLOR', options: COLOR_OPTIONS },
        { type: 'input_statement', name: 'ROWS' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_table_row',
      tooltip: 'Satu baris di dalam tabel (<tr>) — isi dengan blok <td>.',
      message0: '<tr> %1 </tr>',
      args0: [{ type: 'input_statement', name: 'CELLS' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_table_cell',
      tooltip: 'Satu sel/kotak di dalam baris tabel (<td>).',
      message0: '<td> %1 </td>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_list_ordered',
      tooltip: 'Daftar bernomor (<ol>) — isi dengan blok <li>.',
      message0: '<ol> tipe %1 mulai %2 %3 </ol>',
      args0: [
        {
          type: 'field_dropdown',
          name: 'TYPE',
          options: [
            ['angka', '1'],
            ['huruf besar', 'A'],
            ['huruf kecil', 'a'],
            ['romawi besar', 'I'],
            ['romawi kecil', 'i'],
          ],
        },
        { type: 'field_number', name: 'START', value: 1, min: 1, precision: 1 },
        { type: 'input_statement', name: 'ITEMS' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_header',
      tooltip: 'Bagian atas halaman, biasanya berisi judul/menu (<header>).',
      message0: '<header> %1 </header>',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_main',
      tooltip: 'Bagian isi utama halaman (<main>).',
      message0: '<main> %1 </main>',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_footer',
      tooltip: 'Bagian bawah halaman, biasanya berisi hak cipta (<footer>).',
      message0: '<footer> %1 </footer>',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_text',
      tooltip: 'Sepotong teks biasa untuk diisikan ke blok lain.',
      message0: '<> %1',
      args0: [{ type: 'field_input', name: 'VALUE', text: 'Tulis di sini' }],
      output: 'String',
      style: 'content_blocks',
    },
    {
      type: 'html_image_asset',
      tooltip: 'Menampilkan gambar dari pustaka aset (<img>).',
      message0: '<img src= %1 alt= %2 lebar %3 piksel >',
      args0: [
        { type: 'field_dropdown', name: 'ASSET', options: () => getAssetOptions() },
        { type: 'field_input', name: 'ALT', text: '' },
        { type: 'field_number', name: 'WIDTH', value: 0, min: 0, precision: 1 },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_image_url',
      tooltip: 'Menampilkan gambar dari alamat web (<img>).',
      message0: '<img src= %1 alt= %2 lebar %3 piksel >',
      args0: [
        { type: 'field_input', name: 'URL', text: 'https://' },
        { type: 'field_input', name: 'ALT', text: '' },
        { type: 'field_number', name: 'WIDTH', value: 0, min: 0, precision: 1 },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_link',
      tooltip: 'Tautan yang bisa diklik ke halaman lain (<a>).',
      message0: '<a href= %1 > %2 </a> tab baru? %3',
      args0: [
        { type: 'field_input', name: 'URL', text: 'https://' },
        { type: 'field_input', name: 'LABEL', text: 'Tulis di sini' },
        { type: 'field_checkbox', name: 'NEW_TAB', checked: false },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_button',
      tooltip: 'Tombol yang bisa ditekan (<button>).',
      message0: '<button> %1 </button>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_hr',
      tooltip: 'Garis pemisah mendatar (<hr>).',
      message0: '<hr>',
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_style_color',
      tooltip: 'Mengubah warna teks isinya (CSS color).',
      message0: 'color: %1 %2',
      args0: [
        { type: 'field_dropdown', name: 'COLOR', options: COLOR_OPTIONS },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_bg',
      tooltip: 'Mengubah warna latar isinya (CSS background).',
      message0: 'background: %1 %2',
      args0: [
        { type: 'field_dropdown', name: 'COLOR', options: COLOR_OPTIONS },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_align',
      tooltip: 'Mengatur perataan teks isinya: kiri, tengah, kanan (CSS text-align).',
      message0: 'text-align: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'ALIGN',
          options: [
            ['kiri', 'left'],
            ['tengah', 'center'],
            ['kanan', 'right'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_size',
      tooltip: 'Mengubah ukuran teks isinya (CSS font-size).',
      message0: 'font-size: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'SIZE',
          options: [
            ['kecil', '0.85rem'],
            ['sedang', '1rem'],
            ['besar', '1.5rem'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_bold',
      tooltip: 'Menebalkan teks isinya (CSS font-weight: bold).',
      message0: 'font-weight: bold %1',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_italic',
      tooltip: 'Memiringkan teks isinya (CSS font-style: italic).',
      message0: 'font-style: italic %1',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_padding',
      tooltip: 'Menambah jarak di dalam kotak isinya (CSS padding).',
      message0: 'padding: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'SIZE',
          options: [
            ['kecil', '8px'],
            ['sedang', '16px'],
            ['besar', '32px'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_margin',
      tooltip: 'Menambah jarak di luar kotak isinya (CSS margin).',
      message0: 'margin: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'SIZE',
          options: [
            ['kecil', '8px'],
            ['sedang', '16px'],
            ['besar', '32px'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_radius',
      tooltip: 'Melengkungkan sudut kotak isinya (CSS border-radius).',
      message0: 'border-radius: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'SIZE',
          options: [
            ['kecil', '8px'],
            ['sedang', '16px'],
            ['bulat', '9999px'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_shadow',
      tooltip: 'Menambah bayangan lembut di sekitar isinya (CSS box-shadow).',
      message0: 'box-shadow: lembut %1',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_font',
      tooltip: 'Mengubah jenis huruf isinya (CSS font-family).',
      message0: 'font-family: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'FONT',
          options: [
            ['standar', 'inherit'],
            ['rapi', 'Georgia, serif'],
            ['mesin ketik', '"Courier New", monospace'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
  ]);
}
