import * as Blockly from 'blockly/core';

const COLOR_OPTIONS: [string, string][] = [
  ['hitam', '#000000'],
  ['putih', '#ffffff'],
  ['merah', '#e53935'],
  ['jingga', '#fb8c00'],
  ['kuning', '#fdd835'],
  ['hijau', '#43a047'],
  ['biru', '#1e88e5'],
  ['ungu', '#8e24aa'],
  ['merah muda', '#ec407a'],
  ['abu-abu', '#9e9e9e'],
];

let getAssetOptions: () => [string, string][] = () => [['(tidak ada gambar)', '']];

export function setHtmlAssetOptionsProvider(fn: () => [string, string][]): void {
  getAssetOptions = fn;
}

export const HTML_BLOCK_TYPES = [
  'html_document',
  'html_head',
  'html_body',
  'html_title',
  'html_section',
  'html_heading',
  'html_paragraph',
  'html_list',
  'html_list_item',
  'html_text',
  'html_image_asset',
  'html_image_url',
  'html_link',
  'html_button',
  'html_hr',
  'html_style_color',
  'html_style_bg',
  'html_style_align',
  'html_style_size',
  'html_style_bold',
  'html_style_italic',
] as const;

export function registerHtmlBlocks(): void {
  Blockly.defineBlocksWithJsonArray([
    {
      type: 'html_document',
      message0: '<html> %1 </html>',
      args0: [{ type: 'input_statement', name: 'CONTENT' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Kerangka satu halaman HTML lengkap (<html>).',
    },
    {
      type: 'html_head',
      message0: '<head> %1 </head>',
      args0: [{ type: 'input_statement', name: 'CONTENT' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Bagian info halaman yang tak tampil di layar, mis. judul tab (<head>).',
    },
    {
      type: 'html_body',
      message0: '<body> %1 </body>',
      args0: [{ type: 'input_statement', name: 'CONTENT' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Isi halaman yang tampil di layar (<body>).',
    },
    {
      type: 'html_title',
      message0: '<title> %1 </title>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
      tooltip: 'Judul halaman yang muncul di tab browser (<title>).',
    },
    {
      type: 'html_section',
      tooltip: 'Satu bagian halaman untuk mengelompokkan isi (<section>).',
      message0: '<section> %1 </section>',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_heading',
      tooltip: 'Judul bagian dengan ukuran h1, h2, atau h3 (<h1>).',
      message0: '%1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'LEVEL',
          options: [
            ['<h1>', 'h1'],
            ['<h2>', 'h2'],
            ['<h3>', 'h3'],
          ],
        },
        { type: 'input_value', name: 'TEXT', check: 'String' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_paragraph',
      tooltip: 'Satu paragraf teks (<p>).',
      message0: '<p> %1 </p>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_list',
      tooltip: 'Daftar berpoin (<ul>) — isi dengan blok <li>.',
      message0: '<ul> %1 </ul>',
      args0: [{ type: 'input_statement', name: 'ITEMS' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_list_item',
      tooltip: 'Satu butir di dalam daftar (<li>).',
      message0: '<li> %1 </li>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'structure_blocks',
    },
    {
      type: 'html_text',
      tooltip: 'Sepotong teks biasa untuk diisikan ke blok lain.',
      message0: '<> %1',
      args0: [{ type: 'field_input', name: 'VALUE', text: 'Tulis di sini' }],
      output: 'String',
      style: 'content_blocks',
    },
    {
      type: 'html_image_asset',
      tooltip: 'Menampilkan gambar dari pustaka aset (<img>).',
      message0: '<img src= %1 alt= %2 >',
      args0: [
        { type: 'field_dropdown', name: 'ASSET', options: () => getAssetOptions() },
        { type: 'field_input', name: 'ALT', text: '' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_image_url',
      tooltip: 'Menampilkan gambar dari alamat web (<img>).',
      message0: '<img src= %1 alt= %2 >',
      args0: [
        { type: 'field_input', name: 'URL', text: 'https://' },
        { type: 'field_input', name: 'ALT', text: '' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_link',
      tooltip: 'Tautan yang bisa diklik ke halaman lain (<a>).',
      message0: '<a href= %1 > %2 </a>',
      args0: [
        { type: 'field_input', name: 'URL', text: 'https://' },
        { type: 'field_input', name: 'LABEL', text: 'Tulis di sini' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_button',
      tooltip: 'Tombol yang bisa ditekan (<button>).',
      message0: '<button> %1 </button>',
      args0: [{ type: 'input_value', name: 'TEXT', check: 'String' }],
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_hr',
      tooltip: 'Garis pemisah mendatar (<hr>).',
      message0: '<hr>',
      previousStatement: null,
      nextStatement: null,
      style: 'content_blocks',
    },
    {
      type: 'html_style_color',
      tooltip: 'Mengubah warna teks isinya (CSS color).',
      message0: 'color: %1 %2',
      args0: [
        { type: 'field_dropdown', name: 'COLOR', options: COLOR_OPTIONS },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_bg',
      tooltip: 'Mengubah warna latar isinya (CSS background).',
      message0: 'background: %1 %2',
      args0: [
        { type: 'field_dropdown', name: 'COLOR', options: COLOR_OPTIONS },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_align',
      tooltip: 'Mengatur perataan teks isinya: kiri, tengah, kanan (CSS text-align).',
      message0: 'text-align: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'ALIGN',
          options: [
            ['kiri', 'left'],
            ['tengah', 'center'],
            ['kanan', 'right'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_size',
      tooltip: 'Mengubah ukuran teks isinya (CSS font-size).',
      message0: 'font-size: %1 %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'SIZE',
          options: [
            ['kecil', '0.85rem'],
            ['sedang', '1rem'],
            ['besar', '1.5rem'],
          ],
        },
        { type: 'input_statement', name: 'BODY' },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_bold',
      tooltip: 'Menebalkan teks isinya (CSS font-weight: bold).',
      message0: 'font-weight: bold %1',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
    {
      type: 'html_style_italic',
      tooltip: 'Memiringkan teks isinya (CSS font-style: italic).',
      message0: 'font-style: italic %1',
      args0: [{ type: 'input_statement', name: 'BODY' }],
      previousStatement: null,
      nextStatement: null,
      style: 'style_blocks',
    },
  ]);
}
