import type * as Blockly from 'blockly/core';

const textShadow = (value = 'Tulis di sini') => ({
  shadow: { type: 'html_text', fields: { VALUE: value } },
});

export const htmlToolbox: Blockly.utils.toolbox.ToolboxDefinition = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: 'Struktur',
      categorystyle: 'structure_category',
      cssconfig: {
        container: 'blocklyToolboxCategory kodako-cat kodako-cat--structure',
        icon: 'kodako-cat-icon kodako-cat-icon--structure',
      },
      contents: [
        { kind: 'block', type: 'html_document' },
        { kind: 'block', type: 'html_head' },
        { kind: 'block', type: 'html_title', inputs: { TEXT: textShadow('Halaman Saya') } },
        { kind: 'block', type: 'html_body' },
        { kind: 'block', type: 'html_header' },
        { kind: 'block', type: 'html_nav' },
        { kind: 'block', type: 'html_main' },
        { kind: 'block', type: 'html_footer' },
        { kind: 'block', type: 'html_section' },
        { kind: 'block', type: 'html_row' },
      ],
    },
    {
      kind: 'category',
      name: 'Teks',
      categorystyle: 'text_category',
      cssconfig: {
        container: 'blocklyToolboxCategory kodako-cat kodako-cat--text',
        icon: 'kodako-cat-icon kodako-cat-icon--text',
      },
      contents: [
        { kind: 'block', type: 'html_heading', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_paragraph', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_text' },
        { kind: 'block', type: 'html_strong', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_em', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_mark', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_blockquote' },
        { kind: 'block', type: 'html_pre' },
        { kind: 'block', type: 'html_code', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_hr' },
        { kind: 'block', type: 'html_br' },
      ],
    },
    {
      kind: 'category',
      name: 'Tabel & Daftar',
      categorystyle: 'table_category',
      cssconfig: {
        container: 'blocklyToolboxCategory kodako-cat kodako-cat--table',
        icon: 'kodako-cat-icon kodako-cat-icon--table',
      },
      contents: [
        { kind: 'block', type: 'html_list' },
        { kind: 'block', type: 'html_list_ordered' },
        { kind: 'block', type: 'html_list_item', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_table' },
        { kind: 'block', type: 'html_table_row' },
        { kind: 'block', type: 'html_table_cell', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_table_header_cell', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_caption', inputs: { TEXT: textShadow() } },
      ],
    },
    {
      kind: 'category',
      name: 'Media',
      categorystyle: 'media_category',
      cssconfig: {
        container: 'blocklyToolboxCategory kodako-cat kodako-cat--media',
        icon: 'kodako-cat-icon kodako-cat-icon--media',
      },
      contents: [
        { kind: 'block', type: 'html_image_asset' },
        { kind: 'block', type: 'html_image_url' },
        { kind: 'block', type: 'html_figure' },
        { kind: 'block', type: 'html_figcaption', inputs: { TEXT: textShadow() } },
        { kind: 'block', type: 'html_audio' },
        { kind: 'block', type: 'html_video' },
        { kind: 'block', type: 'html_link' },
      ],
    },
    {
      kind: 'category',
      name: 'Formulir & Interaktif',
      categorystyle: 'form_category',
      cssconfig: {
        container: 'blocklyToolboxCategory kodako-cat kodako-cat--form',
        icon: 'kodako-cat-icon kodako-cat-icon--form',
      },
      contents: [
        { kind: 'block', type: 'html_form' },
        { kind: 'block', type: 'html_label', inputs: { TEXT: textShadow('Nama:') } },
        { kind: 'block', type: 'html_input_text' },
        { kind: 'block', type: 'html_input_checkbox', inputs: { TEXT: textShadow('Setuju') } },
        { kind: 'block', type: 'html_input_radio', inputs: { TEXT: textShadow('Pilihan A') } },
        { kind: 'block', type: 'html_textarea' },
        { kind: 'block', type: 'html_select' },
        { kind: 'block', type: 'html_option', inputs: { TEXT: textShadow('Opsi 1') } },
        { kind: 'block', type: 'html_button', inputs: { TEXT: textShadow('Kirim') } },
        { kind: 'block', type: 'html_details' },
        { kind: 'block', type: 'html_summary', inputs: { TEXT: textShadow('Klik untuk info') } },
      ],
    },
    {
      kind: 'category',
      name: 'Gaya',
      categorystyle: 'style_category',
      cssconfig: {
        container: 'blocklyToolboxCategory kodako-cat kodako-cat--style',
        icon: 'kodako-cat-icon kodako-cat-icon--style',
      },
      contents: [
        { kind: 'block', type: 'html_style_color' },
        { kind: 'block', type: 'html_style_bg' },
        { kind: 'block', type: 'html_style_align' },
        { kind: 'block', type: 'html_style_size' },
        { kind: 'block', type: 'html_style_bold' },
        { kind: 'block', type: 'html_style_italic' },
        { kind: 'block', type: 'html_style_padding' },
        { kind: 'block', type: 'html_style_margin' },
        { kind: 'block', type: 'html_style_radius' },
        { kind: 'block', type: 'html_style_shadow' },
        { kind: 'block', type: 'html_style_font' },
      ],
    },
  ],
};
